(() => {
  const state={api:'',token:'',user:null,data:{items:[],masuk:[],keluar:[],rusak:[],settings:{}}};
  const $=s=>document.querySelector(s); const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const money=v=>Number(v||0).toLocaleString('id-ID');
  function toast(msg,err=false){const t=$('#toast');t.textContent=msg;t.className='toast show'+(err?' err':'');setTimeout(()=>t.className='toast',3000)}
  function saveLocal(){localStorage.setItem('smartInvApi',state.api);localStorage.setItem('smartInvToken',state.token);localStorage.setItem('smartInvUser',JSON.stringify(state.user||null))}
  async function call(action,payload={}){
    if(!state.api) throw Error('URL Apps Script belum diisi.');
    const r=await fetch(state.api,{method:'POST',body:JSON.stringify({action,token:state.token,...payload})});
    const text=await r.text();let d;try{d=JSON.parse(text)}catch(e){throw Error('Respons server bukan JSON. Pastikan URL Web App /exec benar.')}
    if(!d.ok) throw Error(d.error||'Permintaan gagal'); return d;
  }
  async function login(){try{state.api=$('#apiUrl').value.trim();const u=$('#username').value.trim(),p=$('#password').value; if(!state.api)throw Error('Masukkan URL Google Apps Script Web App.');const d=await call('login',{username:u,password:p});state.token=d.token;state.user=d.user;saveLocal();await load();$('#loginView').classList.add('hidden');$('#app').classList.remove('hidden');$('#userInfo').textContent=`${d.user.name} • ${d.user.role}`;renderDashboard();toast('Login berhasil')}catch(e){toast(e.message,true)}}
  async function load(){const d=await call('bootstrap');state.data=d.data||state.data;renderCurrent()}
  function nav(page){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$('#page-'+page).classList.remove('hidden');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('#pageTitle').textContent={dashboard:'Dashboard',inventaris:'Inventaris',transaksi:'Transaksi',pengaturan:'Pengaturan'}[page];renderCurrent()}
  function renderCurrent(){const p=[...document.querySelectorAll('.page')].find(x=>!x.classList.contains('hidden'))?.id.replace('page-','');if(p==='dashboard')renderDashboard();if(p==='inventaris')renderInventaris();if(p==='transaksi')renderTransaksi();if(p==='pengaturan')renderSettings()}
  function renderDashboard(){const d=state.data,items=d.items||[];const total=items.reduce((a,x)=>a+Number(x.jumlah||0),0);const baik=items.filter(x=>String(x.kondisi).toLowerCase()==='baik').length;$('#page-dashboard').innerHTML=`<div class="cards"><div class="card"><div class="muted">Jenis Inventaris</div><div class="metric">${money(items.length)}</div></div><div class="card"><div class="muted">Total Barang</div><div class="metric">${money(total)}</div></div><div class="card"><div class="muted">Kondisi Baik</div><div class="metric">${money(baik)}</div></div><div class="card"><div class="muted">Barang Rusak</div><div class="metric">${money((d.rusak||[]).length)}</div></div></div><div class="section"><div class="section-head"><h3>Ringkasan Transaksi</h3></div><div class="cards"><div class="card"><div class="muted">Barang Masuk</div><div class="metric">${money((d.masuk||[]).length)}</div></div><div class="card"><div class="muted">Barang Keluar</div><div class="metric">${money((d.keluar||[]).length)}</div></div><div class="card"><div class="muted">Data Rusak</div><div class="metric">${money((d.rusak||[]).length)}</div></div><div class="card"><div class="muted">Database</div><div class="metric" style="font-size:18px;color:var(--ok)">TERHUBUNG</div></div></div></div><div class="section"><div class="section-head"><h3>Inventaris Terbaru</h3><button class="primary" onclick="window.__newItem()">+ Tambah Barang</button></div>${tableItems(items.slice(-10).reverse())}</div>`}
  function tableItems(items){if(!items.length)return'<div class="card empty">Belum ada data inventaris.</div>';return`<div class="table-wrap"><table class="table"><thead><tr><th>Kode</th><th>Nama</th><th>Kategori</th><th>Ruangan</th><th>Jumlah</th><th>Kondisi</th><th>Aksi</th></tr></thead><tbody>${items.map(x=>`<tr><td>${esc(x.kode)}</td><td><b>${esc(x.nama)}</b><br><span class="muted">${esc(x.keterangan)}</span></td><td>${esc(x.kategori)}</td><td>${esc(x.ruangan)}</td><td>${money(x.jumlah)}</td><td><span class="badge ${String(x.kondisi).toLowerCase()==='baik'?'ok':''}">${esc(x.kondisi)}</span></td><td><button class="ghost" onclick="window.__editItem('${esc(x.id)}')">Edit</button> <button class="danger" onclick="window.__delItem('${esc(x.id)}')">Hapus</button></td></tr>`).join('')}</tbody></table></div>`}
  function renderInventaris(){const items=state.data.items||[];$('#page-inventaris').innerHTML=`<div class="section-head"><div class="toolbar"><input id="searchItem" placeholder="Cari kode/nama/kategori..." style="width:290px"></div><button class="primary" onclick="window.__newItem()">+ Tambah Barang</button></div><div id="itemTable">${tableItems(items)}</div>`;$('#searchItem').oninput=()=>{const q=$('#searchItem').value.toLowerCase();$('#itemTable').innerHTML=tableItems(items.filter(x=>[x.kode,x.nama,x.kategori,x.ruangan].some(v=>String(v||'').toLowerCase().includes(q))))}}
  function renderTransaksi(){const d=state.data, rows=[...(d.masuk||[]).map(x=>({...x,_j:'Masuk'})),...(d.keluar||[]).map(x=>({...x,_j:'Keluar'})),...(d.rusak||[]).map(x=>({...x,_j:'Rusak'}))].sort((a,b)=>String(b.tanggal).localeCompare(String(a.tanggal)));$('#page-transaksi').innerHTML=`<div class="section-head"><div class="toolbar"><select id="jenisFilter"><option value="">Semua transaksi</option><option>Masuk</option><option>Keluar</option><option>Rusak</option></select></div><button class="primary" onclick="window.__newTx()">+ Tambah Transaksi</button></div><div id="txTable">${txTable(rows)}</div>`;$('#jenisFilter').onchange=()=>$('#txTable').innerHTML=txTable(rows.filter(x=>!$('#jenisFilter').value||x._j===$('#jenisFilter').value))}
  function txTable(rows){if(!rows.length)return'<div class="card empty">Belum ada transaksi.</div>';return`<div class="table-wrap"><table class="table"><thead><tr><th>Tanggal</th><th>Jenis</th><th>Kode</th><th>Jumlah</th><th>Keterangan</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.tanggal)}</td><td><span class="badge">${esc(x._j)}</span></td><td>${esc(x.kode)}</td><td>${money(x.jumlah)}</td><td>${esc(x.keterangan)}</td></tr>`).join('')}</tbody></table></div>`}
  function renderSettings(){const s=state.data.settings||{};$('#page-pengaturan').innerHTML=`<div class="settings-box"><div class="card"><h3>Identitas Sekolah</h3><label>Nama Sekolah</label><input id="setNama" value="${esc(s.namaSekolah||'SMAN 1 Kota Gajah')}"><label>Kepala Sekolah</label><input id="setKepala" value="${esc(s.kepalaSekolah||'')}"><label>Alamat</label><textarea id="setAlamat">${esc(s.alamat||'')}</textarea><div class="actions"><button class="primary" onclick="window.__saveSettings()">Simpan Pengaturan</button></div></div><div class="card section"><h3>Backup & Restore</h3><p class="muted">Backup menyimpan data inventaris, transaksi, dan pengaturan dalam file JSON.</p><div class="backup-box"><button class="ghost" onclick="window.__backup()">Unduh Backup JSON</button><input id="restoreFile" type="file" accept="application/json"><button class="ghost" onclick="window.__restore()">Restore dari JSON</button></div></div><div class="card section"><h3>Koneksi</h3><div class="muted">URL API aktif</div><div style="word-break:break-all;margin-top:7px">${esc(state.api)}</div></div></div>`}
  function modal(html){const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="modal-card">${html}</div>`;document.body.appendChild(m);return m}
  window.__newItem=()=>itemModal();window.__editItem=id=>itemModal(state.data.items.find(x=>String(x.id)===String(id)));
  function itemModal(item={}){const m=modal(`<div class="modal-head"><h3>${item.id?'Edit':'Tambah'} Inventaris</h3><button class="close">✕</button></div><div class="form-grid"><div><label>Kode Barang *</label><input id="fKode" value="${esc(item.kode)}"></div><div><label>Nama Barang *</label><input id="fNama" value="${esc(item.nama)}"></div><div><label>Kategori</label><input id="fKat" value="${esc(item.kategori)}"></div><div><label>Ruangan</label><input id="fRuang" value="${esc(item.ruangan)}"></div><div><label>Jumlah</label><input id="fJumlah" type="number" min="0" value="${esc(item.jumlah||0)}"></div><div><label>Kondisi</label><select id="fKond"><option ${item.kondisi==='Baik'?'selected':''}>Baik</option><option ${item.kondisi==='Rusak Ringan'?'selected':''}>Rusak Ringan</option><option ${item.kondisi==='Rusak Berat'?'selected':''}>Rusak Berat</option></select></div><div><label>Sumber</label><input id="fSumber" value="${esc(item.sumber)}"></div><div><label>Foto (URL)</label><input id="fFoto" value="${esc(item.foto)}"></div><div class="wide"><label>Keterangan</label><textarea id="fKet">${esc(item.keterangan)}</textarea></div></div><div class="actions"><button class="ghost close2">Batal</button><button class="primary" id="saveItem">Simpan</button></div>`);m.querySelector('.close').onclick=()=>m.remove();m.querySelector('.close2').onclick=()=>m.remove();m.querySelector('#saveItem').onclick=async()=>{try{const d={id:item.id,kode:$('#fKode').value.trim(),nama:$('#fNama').value.trim(),kategori:$('#fKat').value,ruangan:$('#fRuang').value,jumlah:Number($('#fJumlah').value||0),kondisi:$('#fKond').value,sumber:$('#fSumber').value,foto:$('#fFoto').value,keterangan:$('#fKet').value};await call('saveItem',{item:d});m.remove();await load();toast('Data inventaris disimpan')}catch(e){toast(e.message,true)}}}
  window.__delItem=async id=>{if(!confirm('Hapus data inventaris ini?'))return;try{await call('deleteItem',{id});await load();toast('Data dihapus')}catch(e){toast(e.message,true)}};
  window.__newTx=()=>{const m=modal(`<div class="modal-head"><h3>Tambah Transaksi</h3><button class="close">✕</button></div><div class="form-grid"><div><label>Tanggal</label><input id="tDate" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div><label>Jenis</label><select id="tJenis"><option>Masuk</option><option>Keluar</option><option>Rusak</option></select></div><div><label>Kode Barang</label><input id="tKode"></div><div><label>Jumlah</label><input id="tJumlah" type="number" min="1" value="1"></div><div class="wide"><label>Keterangan</label><textarea id="tKet"></textarea></div></div><div class="actions"><button class="ghost close2">Batal</button><button class="primary" id="saveTx">Simpan</button></div>`);m.querySelector('.close').onclick=()=>m.remove();m.querySelector('.close2').onclick=()=>m.remove();m.querySelector('#saveTx').onclick=async()=>{try{await call('saveTransaction',{transaction:{tanggal:$('#tDate').value,jenis:$('#tJenis').value,kode:$('#tKode').value.trim(),jumlah:Number($('#tJumlah').value||0),keterangan:$('#tKet').value}});m.remove();await load();toast('Transaksi disimpan')}catch(e){toast(e.message,true)}}};
  window.__saveSettings=async()=>{try{await call('saveSettings',{settings:{namaSekolah:$('#setNama').value,kepalaSekolah:$('#setKepala').value,alamat:$('#setAlamat').value}});await load();toast('Pengaturan disimpan')}catch(e){toast(e.message,true)}};
  window.__backup=()=>{const blob=new Blob([JSON.stringify(state.data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='SMART_INVENTARIS_BACKUP.json';a.click();URL.revokeObjectURL(a.href)};
  window.__restore=async()=>{const f=$('#restoreFile').files[0];if(!f)return toast('Pilih file backup JSON.',true);if(!confirm('Restore akan mengganti data inventaris dan transaksi pada database. Lanjutkan?'))return;try{const d=JSON.parse(await f.text());await call('restore',{data:d});await load();toast('Restore berhasil')}catch(e){toast(e.message,true)}};
  $('#loginBtn').onclick=login;$('#password').onkeydown=e=>{if(e.key==='Enter')login()};$('#refreshBtn').onclick=async()=>{try{await load();toast('Data diperbarui')}catch(e){toast(e.message,true)}};$('#logoutBtn').onclick=()=>{state.token='';state.user=null;saveLocal();$('#app').classList.add('hidden');$('#loginView').classList.remove('hidden')};document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>nav(b.dataset.page));
  const cfg=(window.SMART_INVENTARIS_CONFIG||{}).API_URL||localStorage.getItem('smartInvApi')||'';$('#apiUrl').value=cfg;
  const token=localStorage.getItem('smartInvToken'),user=JSON.parse(localStorage.getItem('smartInvUser')||'null');if(token&&cfg){state.api=cfg;state.token=token;state.user=user;load().then(()=>{if(state.data){$('#loginView').classList.add('hidden');$('#app').classList.remove('hidden');$('#userInfo').textContent=`${user?.name||''} • ${user?.role||''}`;renderDashboard()}}).catch(()=>{})}
})();
