(() => {
  const state={api:'',token:'',user:null,data:{items:[],masuk:[],keluar:[],rusak:[],settings:{},aktivitas:[]}};
  const $=s=>document.querySelector(s);
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const money=v=>Number(v||0).toLocaleString('id-ID');
  const months=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];
  const monthShort=['Jan','Feb','Mar','Apr','Mei','Jun','Jul','Agu','Sep','Okt','Nov','Des'];
  function toast(msg,err=false){const t=$('#toast');t.textContent=msg;t.className='toast show'+(err?' err':'');setTimeout(()=>t.className='toast',3200)}
  function saveLocal(){localStorage.setItem('smartInvApi',state.api);localStorage.setItem('smartInvToken',state.token);localStorage.setItem('smartInvUser',JSON.stringify(state.user||null))}
  function getItemByCode(code){return (state.data.items||[]).find(x=>String(x.kode)===String(code))}
  function txRows(){return [...(state.data.masuk||[]).map(x=>({...x,_j:'Masuk'})),...(state.data.keluar||[]).map(x=>({...x,_j:'Keluar'})),...(state.data.rusak||[]).map(x=>({...x,_j:'Rusak'}))].sort((a,b)=>String(b.tanggal).localeCompare(String(a.tanggal)))}
  async function call(action,payload={}){if(!state.api)throw Error('URL Apps Script belum diisi.');const r=await fetch(state.api,{method:'POST',body:JSON.stringify({action,token:state.token,...payload})});const text=await r.text();let d;try{d=JSON.parse(text)}catch(e){throw Error('Respons server bukan JSON. Pastikan URL Web App /exec benar.')}if(!d.ok)throw Error(d.error||'Permintaan gagal');return d}
  async function login(){try{state.api=$('#apiUrl').value.trim();const u=$('#username').value.trim(),p=$('#password').value;if(!state.api)throw Error('Masukkan URL Google Apps Script Web App.');const d=await call('login',{username:u,password:p});state.token=d.token;state.user=d.user;saveLocal();await load();$('#loginView').classList.add('hidden');$('#app').classList.remove('hidden');$('#userInfo').textContent=`${d.user.name} • ${d.user.role}`;renderDashboard();toast('Login berhasil')}catch(e){toast(e.message,true)}}
  async function load(){const d=await call('bootstrap');state.data=d.data||state.data;renderCurrent();updateLogos()}
  function nav(page){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$('#page-'+page).classList.remove('hidden');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('#pageTitle').textContent={dashboard:'Dashboard',inventaris:'Inventaris',transaksi:'Transaksi',laporan:'Laporan',pengaturan:'Pengaturan'}[page];renderCurrent()}
  function renderCurrent(){const p=[...document.querySelectorAll('.page')].find(x=>!x.classList.contains('hidden'))?.id.replace('page-','');if(p==='dashboard')renderDashboard();if(p==='inventaris')renderInventaris();if(p==='transaksi')renderTransaksi();if(p==='laporan')renderLaporan();if(p==='pengaturan')renderSettings();updateLogos()}
  function logoSrc(){const s=state.data.settings||{};return s.logoData||''}
  function updateLogos(){const src=logoSrc();['loginLogo','sideLogo'].forEach(id=>{const el=$('#'+id);if(!el)return;if(src)el.innerHTML=`<img src="${esc(src)}" alt="Logo sekolah">`;else el.textContent='SI'})}
  function renderDashboard(){const d=state.data,items=d.items||[],trs=txRows();const total=items.reduce((a,x)=>a+Number(x.jumlah||0),0),baik=items.reduce((a,x)=>a+(String(x.kondisi).toLowerCase()==='baik'?Number(x.jumlah||0):0),0),rusak=items.reduce((a,x)=>a+(String(x.kondisi).toLowerCase().includes('rusak')?Number(x.jumlah||0):0),0);$('#page-dashboard').innerHTML=`<div class="cards"><div class="card"><div class="metric-label"><div><div class="muted">Jenis Inventaris</div><div class="metric">${money(items.length)}</div></div><div class="metric-icon">▤</div></div></div><div class="card"><div class="metric-label"><div><div class="muted">Total Barang</div><div class="metric">${money(total)}</div></div><div class="metric-icon">▦</div></div></div><div class="card"><div class="metric-label"><div><div class="muted">Kondisi Baik</div><div class="metric">${money(baik)}</div></div><div class="metric-icon">✓</div></div></div><div class="card"><div class="metric-label"><div><div class="muted">Barang Rusak</div><div class="metric">${money(rusak)}</div></div><div class="metric-icon">!</div></div></div></div><div class="section"><div class="section-head"><h3>Grafik Transaksi Bulanan</h3><span class="muted">Data Masuk + Keluar, Januari–Desember</span></div><div class="card chart-card">${monthlyChart(trs)}</div></div><div class="section"><div class="settings-grid"><div class="card"><div class="section-head"><h3>Aktivitas Terbaru</h3><button class="ghost" onclick="window.__refresh()">↻</button></div>${activityList(d,trs)}</div><div class="card"><div class="section-head"><h3>Inventaris Terbaru</h3><button class="primary" onclick="window.__newItem()">+ Tambah Barang</button></div>${tableItems(items.slice(-7).reverse())}</div></div></div>`}
  function monthlyChart(trs){const now=new Date(),year=now.getFullYear(),vals=months.map((_,i)=>trs.filter(x=>{const dt=new Date(x.tanggal);return dt.getFullYear()===year&&dt.getMonth()===i}).reduce((a,x)=>a+Number(x.jumlah||0),0)),max=Math.max(...vals,1);return `<div class="chart">${vals.map((v,i)=>{const h=Math.max(3,Math.round(v/max*190));return `<div class="bar-col"><span class="bar-value" style="--h:${h}px">${money(v)}</span><div class="bar" style="height:${h}px"></div><span class="bar-label">${monthShort[i]}</span></div>`}).join('')}</div><div class="legend"><span><i class="dot"></i>Total transaksi per bulan tahun ${year}</span></div>`}
  function activityList(d,trs){const logs=(d.aktivitas||[]).slice(0,8);if(logs.length)return `<div class="activity">${logs.map(x=>`<div class="activity-row"><span class="activity-dot"></span><div><b>${esc(x.aksi||'Aktivitas')}</b><small>${esc(x.detail||'')} • ${formatDateTime(x.tanggal)}</small></div></div>`).join('')}</div>`;if(!trs.length)return '<div class="empty">Belum ada aktivitas.</div>';return `<div class="activity">${trs.slice(0,8).map(x=>`<div class="activity-row"><span class="activity-dot"></span><div><b>Transaksi ${esc(x._j)}</b><small>${esc(x.kode)} • ${money(x.jumlah)} • ${formatDateTime(x.tanggal)}</small></div></div>`).join('')}</div>`}
  function formatDateTime(v){const s=String(v||'');return s.length>16?s.slice(0,16).replace('T',' '):s}
  function tableItems(items){if(!items.length)return'<div class="card empty">Belum ada data inventaris.</div>';return`<div class="table-wrap"><table class="table"><thead><tr><th>Kode</th><th>Nama</th><th>Kategori</th><th>Ruangan</th><th>Jumlah</th><th>Kondisi</th><th>Aksi</th></tr></thead><tbody>${items.map(x=>`<tr><td>${esc(x.kode)}</td><td><b>${esc(x.nama)}</b><br><span class="muted">${esc(x.keterangan)}</span></td><td>${esc(x.kategori)}</td><td>${esc(x.ruangan)}</td><td>${money(x.jumlah)}</td><td><span class="badge ${String(x.kondisi).toLowerCase()==='baik'?'ok':String(x.kondisi).toLowerCase().includes('rusak')?'bad':''}">${esc(x.kondisi)}</span></td><td><button class="ghost" onclick="window.__editItem('${esc(x.id)}')">Edit</button> <button class="danger" onclick="window.__delItem('${esc(x.id)}')">Hapus</button></td></tr>`).join('')}</tbody></table></div>`}
  function renderInventaris(){const items=state.data.items||[];$('#page-inventaris').innerHTML=`<div class="section-head"><div><h3 style="margin:0">Daftar Inventaris</h3><span class="muted">Cari dan filter barang berdasarkan kode, nama, kategori, atau ruangan.</span></div><button class="primary" onclick="window.__newItem()">+ Tambah Barang</button></div><div class="card no-print" style="margin-bottom:15px"><div class="toolbar"><input id="searchItem" placeholder="🔎 Cari barang..." style="max-width:330px"><select id="katFilter" style="max-width:210px"><option value="">Semua kategori</option>${[...new Set(items.map(x=>x.kategori).filter(Boolean))].sort().map(x=>`<option>${esc(x)}</option>`).join('')}</select><select id="ruangFilter" style="max-width:210px"><option value="">Semua ruangan</option>${[...new Set(items.map(x=>x.ruangan).filter(Boolean))].sort().map(x=>`<option>${esc(x)}</option>`).join('')}</select></div></div><div id="itemTable">${tableItems(items)}</div>`;const apply=()=>{const q=$('#searchItem').value.toLowerCase(),k=$('#katFilter').value,r=$('#ruangFilter').value;$('#itemTable').innerHTML=tableItems(items.filter(x=>(!q||[x.kode,x.nama,x.kategori,x.ruangan,x.sumber].some(v=>String(v||'').toLowerCase().includes(q)))&&(!k||x.kategori===k)&&(!r||x.ruangan===r)))};$('#searchItem').oninput=apply;$('#katFilter').onchange=apply;$('#ruangFilter').onchange=apply}
  function renderTransaksi(){const rows=txRows(),items=state.data.items||[];$('#page-transaksi').innerHTML=`<div class="section-head"><div><h3 style="margin:0">Transaksi Barang</h3><span class="muted">Edit atau hapus transaksi ganda dari kolom Aksi.</span></div><button class="primary" onclick="window.__newTx()">+ Tambah Transaksi</button></div><div class="card no-print" style="margin-bottom:15px"><div class="toolbar"><select id="jenisFilter"><option value="">Semua transaksi</option><option>Masuk</option><option>Keluar</option><option>Rusak</option></select><select id="barangFilter"><option value="">Semua barang</option>${items.map(x=>`<option value="${esc(x.kode)}">${esc(x.kode)} — ${esc(x.nama)}</option>`).join('')}</select><input id="txSearch" placeholder="🔎 Cari keterangan/kode..." style="max-width:280px"></div></div><div id="txTable">${txTable(rows)}</div>`;const apply=()=>{const j=$('#jenisFilter').value,b=$('#barangFilter').value,q=$('#txSearch').value.toLowerCase();$('#txTable').innerHTML=txTable(rows.filter(x=>(!j||x._j===j)&&(!b||x.kode===b)&&(!q||[x.kode,x.keterangan,x.tanggal].some(v=>String(v||'').toLowerCase().includes(q)))))};$('#jenisFilter').onchange=apply;$('#barangFilter').onchange=apply;$('#txSearch').oninput=apply}
  function txTable(rows){if(!rows.length)return'<div class="card empty">Belum ada transaksi.</div>';return`<div class="table-wrap"><table class="table"><thead><tr><th>Tanggal</th><th>Jenis</th><th>Barang</th><th>Jumlah</th><th>Keterangan</th><th>Aksi</th></tr></thead><tbody>${rows.map(x=>{const it=getItemByCode(x.kode);return `<tr><td>${esc(x.tanggal)}</td><td><span class="badge ${x._j==='Masuk'?'ok':x._j==='Keluar'?'':'bad'}">${esc(x._j)}</span></td><td><b>${esc(x.kode)}</b><br><span class="muted">${esc(it?.nama||'Barang tidak ditemukan')}</span></td><td>${money(x.jumlah)}</td><td>${esc(x.keterangan)}</td><td><button class="ghost" onclick="window.__editTx('${esc(x.id)}')">Edit</button> <button class="danger" onclick="window.__delTx('${esc(x.id)}')">Hapus</button></td></tr>`}).join('')}</tbody></table></div>`}
  function allYears(){const ys=[...txRows().map(x=>String(x.tanggal||'').slice(0,4)).filter(Boolean),String(new Date().getFullYear())];return [...new Set(ys)].sort((a,b)=>b.localeCompare(a))}
  function renderLaporan(){const items=state.data.items||[];$('#page-laporan').innerHTML=`<div class="section-head"><div><h3 style="margin:0">Laporan Transaksi</h3><span class="muted">Filter Data Masuk & Data Keluar lalu cetak sebagai PDF.</span></div><button class="primary no-print" onclick="window.__printReport()">🖨 Cetak / PDF</button></div><div class="card no-print"><div class="filter-bar"><select id="repJenis"><option value="">Data Masuk & Keluar</option><option>Masuk</option><option>Keluar</option></select><select id="repBarang"><option value="">Semua jenis barang</option>${items.map(x=>`<option value="${esc(x.kode)}">${esc(x.kode)} — ${esc(x.nama)}</option>`).join('')}</select><select id="repBulan"><option value="">Semua bulan</option>${months.map((m,i)=>`<option value="${i+1}">${m}</option>`).join('')}</select><select id="repTahun">${allYears().map(y=>`<option>${y}</option>`).join('')}<option value="">Semua tahun</option></select><button class="ghost" onclick="window.__resetReport()">Reset</button></div></div><div id="reportArea">${reportView()}</div>`;['repJenis','repBarang','repBulan','repTahun'].forEach(id=>$('#'+id).onchange=()=>$('#reportArea').innerHTML=reportView())}
  function reportView(){const j=$('#repJenis')?.value||'',b=$('#repBarang')?.value||'',m=$('#repBulan')?.value||'',y=$('#repTahun')?.value||'';let rows=txRows().filter(x=>x._j!=='Rusak');rows=rows.filter(x=>(!j||x._j===j)&&(!b||x.kode===b)&&(!m||new Date(x.tanggal).getMonth()+1===Number(m))&&(!y||String(x.tanggal).slice(0,4)===String(y)));const s=state.data.settings||{},logo=logoSrc();const total=rows.reduce((a,x)=>a+Number(x.jumlah||0),0);return `<div class="print-only report-header">${logo?`<img class="report-logo" src="${esc(logo)}">`:''}<div class="report-title"><h1>${esc(s.namaSekolah||'SMAN 1 Kota Gajah')}</h1><p>${esc(s.alamat||'')} </p><p>LAPORAN TRANSAKSI BARANG MASUK & KELUAR</p></div></div><div class="report-summary"><div class="card"><div class="muted">Jumlah Transaksi</div><div class="metric">${money(rows.length)}</div></div><div class="card"><div class="muted">Total Barang</div><div class="metric">${money(total)}</div></div><div class="card"><div class="muted">Periode</div><div class="metric" style="font-size:17px">${esc(periodLabel(m,y))}</div></div></div>${rows.length?`<div class="table-wrap"><table class="table report-table"><thead><tr><th>No</th><th>Tanggal</th><th>Jenis</th><th>Kode</th><th>Nama Barang</th><th>Jumlah</th><th>Keterangan</th></tr></thead><tbody>${rows.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.tanggal)}</td><td>${esc(x._j)}</td><td>${esc(x.kode)}</td><td>${esc(getItemByCode(x.kode)?.nama||'-')}</td><td>${money(x.jumlah)}</td><td>${esc(x.keterangan)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="card empty">Tidak ada data sesuai filter.</div>'}`}
  function periodLabel(m,y){return `${m?months[Number(m)-1]:'Semua Bulan'} ${y||''}`.trim()}
  function renderSettings(){const s=state.data.settings||{},src=s.logoData||'';$('#page-pengaturan').innerHTML=`<div class="settings-box"><div class="settings-grid"><div class="card"><h3>Identitas Sekolah</h3><label>Nama Sekolah</label><input id="setNama" value="${esc(s.namaSekolah||'SMAN 1 Kota Gajah')}"><label>Kepala Sekolah</label><input id="setKepala" value="${esc(s.kepalaSekolah||'')}"><label>Alamat</label><textarea id="setAlamat">${esc(s.alamat||'')}</textarea><label>Logo Sekolah (JPG/JPEG/PNG)</label><input id="setLogo" type="file" accept="image/png,image/jpeg,.jpg,.jpeg,.png"><div class="logo-preview" id="logoPreview">${src?`<img src="${esc(src)}" alt="Logo">`:'<span class="muted">Belum ada logo</span>'}</div><small class="muted">Upload langsung dari komputer/HP, tidak perlu URL.</small><div class="actions"><button class="primary" onclick="window.__saveSettings()">Simpan Pengaturan</button></div></div><div><div class="card"><h3>Backup & Restore</h3><p class="muted">Backup menyimpan inventaris, transaksi, logo, dan pengaturan.</p><div class="backup-box"><button class="ghost" onclick="window.__backup()">Unduh Backup JSON</button><input id="restoreFile" type="file" accept="application/json"><button class="ghost" onclick="window.__restore()">Restore dari JSON</button></div></div><div class="card section"><h3>Koneksi</h3><div class="muted">URL API aktif</div><div style="word-break:break-all;margin-top:7px">${esc(state.api)}</div></div></div></div></div>`;$('#setLogo').onchange=async()=>{try{const f=$('#setLogo').files[0];if(!f)return;const data=await imageToDataUrl(f,420,0.78);$('#logoPreview').innerHTML=`<img src="${esc(data)}" alt="Logo">`;$('#setLogo').dataset.data=data}catch(e){toast(e.message,true)}}}
  function modal(html){const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="modal-card">${html}</div>`;document.body.appendChild(m);return m}
  window.__newItem=()=>itemModal();window.__editItem=id=>itemModal(state.data.items.find(x=>String(x.id)===String(id)));
  function itemModal(item={}){const m=modal(`<div class="modal-head"><h3>${item.id?'Edit':'Tambah'} Inventaris</h3><button class="close">✕</button></div><div class="form-grid"><div><label>Kode Barang *</label><input id="fKode" value="${esc(item.kode)}"></div><div><label>Nama Barang *</label><input id="fNama" value="${esc(item.nama)}"></div><div><label>Kategori</label><input id="fKat" value="${esc(item.kategori)}"></div><div><label>Ruangan</label><input id="fRuang" value="${esc(item.ruangan)}"></div><div><label>Jumlah</label><input id="fJumlah" type="number" min="0" value="${esc(item.jumlah||0)}"></div><div><label>Kondisi</label><select id="fKond"><option ${item.kondisi==='Baik'?'selected':''}>Baik</option><option ${item.kondisi==='Rusak Ringan'?'selected':''}>Rusak Ringan</option><option ${item.kondisi==='Rusak Berat'?'selected':''}>Rusak Berat</option></select></div><div><label>Sumber</label><input id="fSumber" value="${esc(item.sumber)}"></div><div class="wide"><label>Keterangan</label><textarea id="fKet">${esc(item.keterangan)}</textarea></div></div><div class="actions"><button class="ghost close2">Batal</button><button class="primary" id="saveItem">Simpan</button></div>`);m.querySelector('.close').onclick=()=>m.remove();m.querySelector('.close2').onclick=()=>m.remove();m.querySelector('#saveItem').onclick=async()=>{try{const d={id:item.id,kode:$('#fKode').value.trim(),nama:$('#fNama').value.trim(),kategori:$('#fKat').value,ruangan:$('#fRuang').value,jumlah:Number($('#fJumlah').value||0),kondisi:$('#fKond').value,sumber:$('#fSumber').value,foto:item.foto||'',keterangan:$('#fKet').value};await call('saveItem',{item:d});m.remove();await load();toast('Data inventaris disimpan')}catch(e){toast(e.message,true)}}}
  window.__delItem=async id=>{if(!confirm('Hapus data inventaris ini?'))return;try{await call('deleteItem',{id});await load();toast('Data inventaris dihapus')}catch(e){toast(e.message,true)}};
  window.__newTx=()=>txModal();
  window.__editTx=id=>{const x=txRows().find(v=>String(v.id)===String(id));if(x)txModal(x)};
  function txModal(tx={}){const items=state.data.items||[];const m=modal(`<div class="modal-head"><h3>${tx.id?'Edit':'Tambah'} Transaksi</h3><button class="close">✕</button></div><div class="form-grid"><div><label>Tanggal</label><input id="tDate" type="date" value="${esc(tx.tanggal||new Date().toISOString().slice(0,10))}"></div><div><label>Jenis Transaksi</label><select id="tJenis"><option ${tx._j==='Masuk'?'selected':''}>Masuk</option><option ${tx._j==='Keluar'?'selected':''}>Keluar</option><option ${tx._j==='Rusak'?'selected':''}>Rusak</option></select></div><div class="wide"><label>Barang</label><select id="tKode"><option value="">Pilih barang</option>${items.map(x=>`<option value="${esc(x.kode)}" ${String(tx.kode)===String(x.kode)?'selected':''}>${esc(x.kode)} — ${esc(x.nama)}</option>`).join('')}</select></div><div><label>Jumlah</label><input id="tJumlah" type="number" min="1" value="${esc(tx.jumlah||1)}"></div><div class="wide"><label>Keterangan</label><textarea id="tKet">${esc(tx.keterangan)}</textarea></div></div><div class="actions"><button class="ghost close2">Batal</button><button class="primary" id="saveTx">Simpan</button></div>`);m.querySelector('.close').onclick=()=>m.remove();m.querySelector('.close2').onclick=()=>m.remove();m.querySelector('#saveTx').onclick=async()=>{try{await call('saveTransaction',{transaction:{id:tx.id,tanggal:$('#tDate').value,jenis:$('#tJenis').value,kode:$('#tKode').value,jumlah:Number($('#tJumlah').value||0),keterangan:$('#tKet').value}});m.remove();await load();toast('Transaksi disimpan')}catch(e){toast(e.message,true)}}}
  window.__delTx=async id=>{if(!confirm('Hapus transaksi ini? Data akan dihapus dari database. Lanjutkan?'))return;try{await call('deleteTransaction',{id});await load();toast('Transaksi dihapus')}catch(e){toast(e.message,true)}};
  window.__saveSettings=async()=>{try{const file=$('#setLogo').files[0],data=$('#setLogo').dataset.data||logoSrc();let logo=data;if(file&&!data)logo=await imageToDataUrl(file,420,.78);await call('saveSettings',{settings:{namaSekolah:$('#setNama').value,kepalaSekolah:$('#setKepala').value,alamat:$('#setAlamat').value,logoData:logo}});await load();toast('Pengaturan dan logo disimpan')}catch(e){toast(e.message,true)}};
  window.__backup=()=>{const blob=new Blob([JSON.stringify(state.data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='SMART_INVENTARIS_BACKUP.json';a.click();URL.revokeObjectURL(a.href)};
  window.__restore=async()=>{const f=$('#restoreFile').files[0];if(!f)return toast('Pilih file backup JSON.',true);if(!confirm('Restore akan mengganti data inventaris, transaksi, logo, dan pengaturan pada database. Lanjutkan?'))return;try{const d=JSON.parse(await f.text());await call('restore',{data:d});await load();toast('Restore berhasil')}catch(e){toast(e.message,true)}};
  window.__refresh=async()=>{try{await load();toast('Data diperbarui')}catch(e){toast(e.message,true)}};
  window.__resetReport=()=>{['repJenis','repBarang','repBulan'].forEach(id=>$('#'+id).value='');$('#repTahun').value=String(new Date().getFullYear());$('#reportArea').innerHTML=reportView()};
  window.__printReport=()=>{document.title='Laporan Inventaris - SMAN 1 Kota Gajah';window.print();setTimeout(()=>document.title='SMART INVENTARIS — SMAN 1 Kota Gajah',500)};
  async function imageToDataUrl(file,max,quality){if(!/^image\/(png|jpeg)$/.test(file.type))throw Error('Logo harus JPG/JPEG/PNG.');return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));const ctx=c.getContext('2d');ctx.drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',quality))};img.onerror=()=>reject(Error('File gambar tidak dapat dibaca.'));img.src=r.result};r.onerror=()=>reject(Error('Gagal membaca file logo.'));r.readAsDataURL(file)})}
  $('#loginBtn').onclick=login;$('#password').onkeydown=e=>{if(e.key==='Enter')login()};$('#refreshBtn').onclick=window.__refresh;$('#logoutBtn').onclick=()=>{state.token='';state.user=null;localStorage.removeItem('smartInvToken');localStorage.removeItem('smartInvUser');$('#app').classList.add('hidden');$('#loginView').classList.remove('hidden')};document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>nav(b.dataset.page));
  const cfg=(window.SMART_INVENTARIS_CONFIG||{}).API_URL||localStorage.getItem('smartInvApi')||'';$('#apiUrl').value=cfg;const token=localStorage.getItem('smartInvToken'),user=JSON.parse(localStorage.getItem('smartInvUser')||'null');if(token&&cfg){state.api=cfg;state.token=token;state.user=user;load().then(()=>{if(state.data){$('#loginView').classList.add('hidden');$('#app').classList.remove('hidden');$('#userInfo').textContent=`${user?.name||''} • ${user?.role||''}`;renderDashboard()}}).catch(()=>{})}
})();
